apiVersion: v1
kind: Service
metadata:
  name: cicd-k8s-monitoring-service
  labels:
    app: cicd-k8s-monitoring-app
spec:
  type: NodePort
  selector:
    app: cicd-k8s-monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080